export const vietnameseTrans: { [key: string]: string } = {
  vendor: "đại lý",
  goldPrice: "giá vàng",
  product: "sản phẩm",
  user: "tài khoản",
  staff: "nguời dùng",
  admin: "quản trị viên",
  contact: "số điện thoại",
  relative: "người thân nhân viên",
  order: "đơn hàng",
  cashDrawer: "tủ thu ngân",
  manager: "Quản lý",
  sales: "Nhân viên",
  home: "Số điện thoại bàn",
  mobile: "Số di động",
  V99: "Nhẫn tròn trơn Mỹ Linh 99%",
  V98: "Nữ trang vàng y 98%",
  V97: "Nhẫn tròn trơn thị trường 97%",
  V68: "Nữ trang đúc 68%",
  V61: "Vàng tây 61%",
  V65: "Vàng 65%",
  V41: "Trắng 41,6%",
  category_V99: "vàng 99%",
  category_V98: "vàng 98%",
  category_V97: "vàng 97%",
  category_V68: "vàng 68%",
  category_V65: "vàng 65%",
  category_V61: "vàng 61%",
  category_V41: "vàng 41,6%",
  necklace: "dây chuyền",
  bracelet: "lắc tay",
  ring: "nhẫn",
  other: "khác",
};
